modLoader = "javafml"
loaderVersion = "[35,)"
#issueTrackerURL = "https://github.com/FrixionCoffee/SoundBootMod/issues"
license = "Creative Commons Zero v1.0 Universal"

[[mods]]
modId = "soundbootmod"
version = "${version}"
displayName = "Sound Boot Mod"
authors = "SugarCoffee"
description = '''
Play music when the title of the game is displayed. It runnable both fabric and forge.
Forum URL: https://forum.civa.jp/viewtopic.php?f=3&t=777
Github: https://github.com/FrixionCoffee/SoundBootMod
'''
#logoFile = ""

[[dependencies.soundbootmod]]
modId = "forge"
mandatory = true
versionRange = "[35,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soundbootmod]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.soundbootmod]]
modId = "architectury"
mandatory = true
versionRange = "[1.1.55,)"
ordering = "AFTER"
side = "BOTH"